### ISSUE TITLE
a-videosphere ambisonic audio

### ISSUE THREAD

**Issue by NicolasINATIC** [digaverse/aframe-resonance-audio-component#4]
Hi,

Is-it possible to have spatial audio with videosphere in a-frame ?

Like this plugin (but it's not downloadable) : https://libraries.io/npm/aframe-ambisonic-audio-component

Thanks,

**Comment by mkungla** [comment]
I guess you could use `MediaStream` / `video.srcObject` like described in https://github.com/digaverse/aframe-resonance-audio-component#dynamic-usage
